### ISSUE TITLE
Support uppercase for function/procedure keywords

### ISSUE THREAD

**Issue by alexhafner** [OraOpenSource/plsql-md-doc#29]
Currently, if in a Package file one of the keywords PROCEDURE or FUNCTION is in uppercase, the entire file will be skipped and the debug output will read

_File: xyz.pkb doesn't appear to have any JavaDoc in it. Skipping_

Naming conventions will often require keywords in uppercase, support for this would be appreciated.

**Comment by martindsouza** [comment]
@alexhafner Can you provide the contents of your package (or dummy file to replicate the issue)?

**Comment by alexhafner** [comment]
@martindsouza  - sure! 

[pmd29.zip](https://github.com/OraOpenSource/plsql-md-doc/files/265912/pmd29.zip)

pmd.zip contains an uppercase PROCEDURE keyword, and as a result none of the functions/procedures are processed and the file is skipped. pmd1.zip works fine as the procedure and function keywords are in lowercase.

**Comment by martindsouza** [comment]
@alexhafner I've applied a fix. Can you please update your copy and test to see if it picks up on the keywords? Should work for `procedure`, `function`, `type`, and `constant` now (all case insensitive).

Let me know the result and if it works we can close the ticket.

**Comment by alexhafner** [comment]
Hi @martindsouza many thanks for the fix! This is looking much better now. I have found one remaining issue, which is the uppercase CONSTANT keyword resulting in the Name and Description being empty in the resulting markdown.

Sample input file: 
[pmd10_pkb.txt](https://github.com/OraOpenSource/plsql-md-doc/files/278384/pmd10_pkb.txt)

Sample markdown file 
[pmd10_output.txt](https://github.com/OraOpenSource/plsql-md-doc/files/278386/pmd10_output.txt)

**Comment by martindsouza** [comment]
@alexhafner I just applied a patch based on your test file. Can you please re-update and try again?

**Comment by alexhafner** [comment]
@martindsouza - that works great now, thank you!
