### ISSUE TITLE
pks vs pkb javadoc

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/plsql-md-doc#34]
I noticed that this project parses the pkb javadoc and ignores the pks one. Maybe it would be worth documenting that.

Would you recommend to stop including the javadoc within the pks file?

**Comment by vincentmorneau** [comment]
I've had packages that generates an `.md` file from pks, others from pkb, but the result is inconsistent when having a javadoc comment block in both pks and pkb.

I can provide examples if needed (in private).

**Comment by martindsouza** [comment]
@vincentmorneau Agreed duplicating documentation is not a good idea. Are all the docs in the `pks` file? If so modify the `"fileFilterRegexp" : "\\.pks$"` option in https://github.com/OraOpenSource/plsql-md-doc/blob/master/docs/config.json.md  Not I changed from `"\\.pk(b|s)$"` to `"\\.pks$"`

**Comment by vincentmorneau** [comment]
That is good enough. Thanks!
