### ISSUE TITLE
Documentation: git update

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/plsql-md-doc#36]
On the readme, `git update` is not a command.

Here's what I use on AFEB:

``` bash
git fetch origin
git reset --hard origin/master
npm install
```

**Comment by vincentmorneau** [comment]
Also, here's the source: http://rogerdudler.github.io/git-guide/ under section "replace local changes"

**Comment by rlove** [comment]
Noticed this today.   I tried the command it appears to do something under my windows machine.   But fails on my Mac OSx Machine.   I will submit a pull request.
