### ISSUE TITLE
JavaScript files

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/plsql-md-doc#39]
I tried running `plsql-md-doc` on a `.js` file with the same javadoc comment structure as instructed for PL/SQL. It did not work.

Would it be useful to include [JSDoc](https://github.com/jsdoc3/jsdoc) as a dependency, or is JavaScript out of scope here?

I'm asking in case you're thinking of making `plsql-md-doc` more an "Oracle Development Documentation Generator"

**Comment by martindsouza** [comment]
This tools primary focus is on PL/SQL code. I understand where you're going for the js files (to support APEX static files and other node.js projects. For that I recommend using the native https://github.com/tj/dox library (which this tool uses).

For now we won't integrate any `.js` support.
