### ISSUE TITLE
displayParams?

### ISSUE THREAD

**Issue by vincentmorneau** [OraOpenSource/plsql-md-doc#55]
Just curious what `displayParams` is for? https://github.com/OraOpenSource/plsql-md-doc/blame/master/templates/package.md#L59

**Comment by martindsouza** [comment]
It was a comment for the closing of the `{{/ifCond}}`. See https://github.com/OraOpenSource/plsql-md-doc/blame/master/templates/package.md#L49

**Comment by vincentmorneau** [comment]
Ha! Thanks, I forgot about handlebars comments notation.
