### ISSUE TITLE
Manual Installation

### ISSUE THREAD

**Issue by pocelka** [OraOpenSource/plsql-md-doc#69]
Hi, 

Is there a way how to perform manual installation? I have some problems with git on my work PC, and I just can't clone the repository. Even if I download repository manually and try to install I can't continue with next step "npm install" as my git issue is blocking also this...

**Comment by martindsouza** [comment]
@pocelka you're right you can download the zip file from Github (which it seems you've done). You'll need to install [Node.js](https://nodejs.org) to run `npm instal`. Unfortunately there's no way of getting around this requirement.
