### ISSUE TITLE
Q : Can this be hosted on server

### ISSUE THREAD

**Issue by lwasylow** [OraOpenSource/plsql-md-doc#76]
Is there a plan to be able run it on a server?
So one install could server few different projects  running via Jenkins and source files based on checkout source control in workspace etc ?

**Comment by martindsouza** [comment]
You could run it on a server. Were you looking for a docker container version of it?

Martin

Martin Giffy D'Souza
martin.dsouza@gmail.com
talkapex.com
oraopensource.com

**Comment by martindsouza** [comment]
You could run it on a server (no difference between that and running it on your laptop) Were you looking for a docker container version of it?
